// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * SSEEvent represents a parsed server-sent event.
 */
export class SSEEvent {
    "type": string;
    "data": json$0.RawMessage;

    /** Creates a new SSEEvent instance. */
    constructor($$source: Partial<SSEEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSEEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SSEEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSEEvent($$parsedSource as Partial<SSEEvent>);
    }
}
