// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CartItem is the input from the Vue frontend when creating an order.
 */
export class CartItem {
    "menu_item_id": string;
    "name_ar": string;
    "price": number;
    "quantity": number;

    /** Creates a new CartItem instance. */
    constructor($$source: Partial<CartItem> = {}) {
        if (!("menu_item_id" in $$source)) {
            this["menu_item_id"] = "";
        }
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("quantity" in $$source)) {
            this["quantity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CartItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CartItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CartItem($$parsedSource as Partial<CartItem>);
    }
}

/**
 * Category represents a menu category.
 */
export class Category {
    "id": string;
    "name_ar": string;
    "sort_order": number;
    "is_active": boolean;
    "updated_at": string;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category($$parsedSource as Partial<Category>);
    }
}

/**
 * InventoryItem represents a back-of-house raw material.
 */
export class InventoryItem {
    "id": string;
    "name_ar": string;
    "base_unit_ar": string;
    "stock_qty": number;
    "low_stock_threshold": number;
    "unit_cost": number;
    "is_active": boolean;
    "updated_at": string;

    /** Creates a new InventoryItem instance. */
    constructor($$source: Partial<InventoryItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("base_unit_ar" in $$source)) {
            this["base_unit_ar"] = "";
        }
        if (!("stock_qty" in $$source)) {
            this["stock_qty"] = 0;
        }
        if (!("low_stock_threshold" in $$source)) {
            this["low_stock_threshold"] = 0;
        }
        if (!("unit_cost" in $$source)) {
            this["unit_cost"] = 0;
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventoryItem($$parsedSource as Partial<InventoryItem>);
    }
}

/**
 * MenuItemWithCategory extends MenuItem with the category name.
 */
export class MenuItemWithCategory {
    "id": string;
    "category_id": string;
    "name_ar": string;
    "price": number;
    "cost_calc_method": string;
    "manual_cost_price": number;
    "cached_auto_cost": number;
    "image_path": string;
    "is_active": boolean;
    "updated_at": string;
    "category_name_ar": string;

    /** Creates a new MenuItemWithCategory instance. */
    constructor($$source: Partial<MenuItemWithCategory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("category_id" in $$source)) {
            this["category_id"] = "";
        }
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = 0;
        }
        if (!("cost_calc_method" in $$source)) {
            this["cost_calc_method"] = "";
        }
        if (!("manual_cost_price" in $$source)) {
            this["manual_cost_price"] = 0;
        }
        if (!("cached_auto_cost" in $$source)) {
            this["cached_auto_cost"] = 0;
        }
        if (!("image_path" in $$source)) {
            this["image_path"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("category_name_ar" in $$source)) {
            this["category_name_ar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuItemWithCategory instance from a string or object.
     */
    static createFrom($$source: any = {}): MenuItemWithCategory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuItemWithCategory($$parsedSource as Partial<MenuItemWithCategory>);
    }
}

/**
 * Order represents a sales transaction in local SQLite.
 */
export class Order {
    "id": string;
    "order_number": string;
    "source": string;
    "table_number": string;
    "status": string;
    "total": number;
    "payment_method": string;
    "device_id": string;
    "created_at": string;
    "updated_at": string;
    "synced": number;

    /** Creates a new Order instance. */
    constructor($$source: Partial<Order> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("order_number" in $$source)) {
            this["order_number"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("table_number" in $$source)) {
            this["table_number"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("payment_method" in $$source)) {
            this["payment_method"] = "";
        }
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("synced" in $$source)) {
            this["synced"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Order instance from a string or object.
     */
    static createFrom($$source: any = {}): Order {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Order($$parsedSource as Partial<Order>);
    }
}

/**
 * OrderItem represents a single line in an order.
 */
export class OrderItem {
    "id": string;
    "order_id": string;
    "menu_item_id": string;
    "quantity": number;
    "unit_price": number;
    "line_total": number;
    "name_ar_snapshot": string;

    /** Creates a new OrderItem instance. */
    constructor($$source: Partial<OrderItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("order_id" in $$source)) {
            this["order_id"] = "";
        }
        if (!("menu_item_id" in $$source)) {
            this["menu_item_id"] = "";
        }
        if (!("quantity" in $$source)) {
            this["quantity"] = 0;
        }
        if (!("unit_price" in $$source)) {
            this["unit_price"] = 0;
        }
        if (!("line_total" in $$source)) {
            this["line_total"] = 0;
        }
        if (!("name_ar_snapshot" in $$source)) {
            this["name_ar_snapshot"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderItem instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderItem($$parsedSource as Partial<OrderItem>);
    }
}

/**
 * OrderWithItems bundles an order with its line items.
 */
export class OrderWithItems {
    "id": string;
    "order_number": string;
    "source": string;
    "table_number": string;
    "status": string;
    "total": number;
    "payment_method": string;
    "device_id": string;
    "created_at": string;
    "updated_at": string;
    "synced": number;
    "items": OrderItem[];

    /** Creates a new OrderWithItems instance. */
    constructor($$source: Partial<OrderWithItems> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("order_number" in $$source)) {
            this["order_number"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("table_number" in $$source)) {
            this["table_number"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("payment_method" in $$source)) {
            this["payment_method"] = "";
        }
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("synced" in $$source)) {
            this["synced"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderWithItems instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderWithItems {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField11_0($$parsedSource["items"]);
        }
        return new OrderWithItems($$parsedSource as Partial<OrderWithItems>);
    }
}

/**
 * RecipeIngredientWithDetails includes inventory item info for display.
 */
export class RecipeIngredientWithDetails {
    "id": string;
    "menu_item_id": string;
    "inventory_item_id": string;
    "quantity": number;
    "updated_at": string;
    "inventory_name_ar": string;
    "base_unit_ar": string;
    "unit_cost": number;

    /** Creates a new RecipeIngredientWithDetails instance. */
    constructor($$source: Partial<RecipeIngredientWithDetails> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("menu_item_id" in $$source)) {
            this["menu_item_id"] = "";
        }
        if (!("inventory_item_id" in $$source)) {
            this["inventory_item_id"] = "";
        }
        if (!("quantity" in $$source)) {
            this["quantity"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("inventory_name_ar" in $$source)) {
            this["inventory_name_ar"] = "";
        }
        if (!("base_unit_ar" in $$source)) {
            this["base_unit_ar"] = "";
        }
        if (!("unit_cost" in $$source)) {
            this["unit_cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecipeIngredientWithDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): RecipeIngredientWithDetails {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecipeIngredientWithDetails($$parsedSource as Partial<RecipeIngredientWithDetails>);
    }
}

/**
 * Table represents a restaurant table (local or from the API).
 */
export class Table {
    "id": string;
    "number": string;
    "token": string;
    "is_active": boolean;
    "synced": number;
    "created_at": string;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("synced" in $$source)) {
            this["synced"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Table($$parsedSource as Partial<Table>);
    }
}

// Private type creation functions
const $$createType0 = OrderItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
