// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService handles local PIN-based authentication.
 * It is Wails-bound so the Vue frontend can call its methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePin updates a user's PIN. Admin-only.
 */
export function ChangePin(userID: string, newPin: string): $CancellablePromise<void> {
    return $Call.ByID(3833139840, userID, newPin);
}

/**
 * CreateUser creates a new local user. Admin-only.
 */
export function CreateUser(nameAr: string, pin: string, role: string): $CancellablePromise<$models.LocalUser | null> {
    return $Call.ByID(4277938414, nameAr, pin, role).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteUser removes a local user. Admin-only. Cannot delete self.
 */
export function DeleteUser(id: string): $CancellablePromise<void> {
    return $Call.ByID(79389305, id);
}

/**
 * GetCurrentUser returns the currently logged-in user, or nil.
 */
export function GetCurrentUser(): $CancellablePromise<$models.LocalUser | null> {
    return $Call.ByID(1235884367).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HasUsers returns true if at least one user exists in the local_users table.
 */
export function HasUsers(): $CancellablePromise<boolean> {
    return $Call.ByID(616007269);
}

/**
 * ListUsers returns all local users (without PIN hash).
 */
export function ListUsers(): $CancellablePromise<$models.LocalUser[]> {
    return $Call.ByID(3488959675).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Login verifies the PIN and sets the current user session.
 */
export function Login(pin: string): $CancellablePromise<$models.LocalUser | null> {
    return $Call.ByID(1049523718, pin).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Logout clears the current user session.
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(558780519);
}

/**
 * SeedDefaultAdmin creates a default admin user if no users exist.
 * Called once at startup.
 */
export function SeedDefaultAdmin(): $CancellablePromise<void> {
    return $Call.ByID(1849626524);
}

// Private type creation functions
const $$createType0 = $models.LocalUser.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
