// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigStoreService is a Wails-bound service for persistent app configuration.
 * It stores key-value pairs in the local SQLite `app_config` table.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get reads a config value by key.
 */
export function Get(key: string): $CancellablePromise<string> {
    return $Call.ByID(1374903552, key);
}

/**
 * GetAPIConnection returns the stored API connection details.
 */
export function GetAPIConnection(): $CancellablePromise<$models.APIConnection> {
    return $Call.ByID(595353320).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDeviceID returns the stored device ID for this POS instance.
 */
export function GetDeviceID(): $CancellablePromise<string> {
    return $Call.ByID(2759179399);
}

/**
 * GetTenantID returns the stored tenant ID.
 */
export function GetTenantID(): $CancellablePromise<string> {
    return $Call.ByID(379449781);
}

/**
 * GetTenantName returns the stored tenant display name.
 */
export function GetTenantName(): $CancellablePromise<string> {
    return $Call.ByID(391265867);
}

/**
 * IsKitchenModeEnabled returns whether the kitchen preparation step is active.
 * Default is false (orders go directly to 'completed').
 */
export function IsKitchenModeEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3944251964);
}

/**
 * IsSetup returns true if the API connection has been configured.
 */
export function IsSetup(): $CancellablePromise<boolean> {
    return $Call.ByID(1932816041);
}

/**
 * ProvisionWithCode provisions this POS using a setup code.
 * Calls the provision endpoint, stores all returned config, and logs in.
 */
export function ProvisionWithCode(apiURL: string, code: string): $CancellablePromise<void> {
    return $Call.ByID(3149707434, apiURL, code);
}

/**
 * Set writes a config value.
 */
export function Set(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3555116652, key, value);
}

/**
 * SetDeviceID stores the device ID and updates the API client.
 */
export function SetDeviceID(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(3796275355, deviceID);
}

/**
 * SetKitchenModeEnabled updates the kitchen mode setting.
 */
export function SetKitchenModeEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2198719036, enabled);
}

/**
 * SetupAPIConnection validates the API connection, stores credentials, and logs in.
 * Username should be in the format "user@tenant-slug".
 */
export function SetupAPIConnection(apiURL: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1510919227, apiURL, username, password);
}

/**
 * TryAutoLogin attempts to login using stored credentials.
 * Returns true if login succeeded, false otherwise.
 */
export function TryAutoLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(1210921787);
}

// Private type creation functions
const $$createType0 = $models.APIConnection.createFrom;
