// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetCategories returns all active categories from local SQLite.
 */
export function GetCategories(): $CancellablePromise<model$0.Category[]> {
    return $Call.ByID(3723352185).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetImageDataURI(imageURL: string): $CancellablePromise<string> {
    return $Call.ByID(1776182208, imageURL);
}

/**
 * GetInventoryItems returns all active inventory items from local SQLite.
 */
export function GetInventoryItems(): $CancellablePromise<model$0.InventoryItem[]> {
    return $Call.ByID(512903821).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLastSyncTime returns the last successful sync timestamp from sync_meta.
 */
export function GetLastSyncTime(): $CancellablePromise<string> {
    return $Call.ByID(468008867);
}

/**
 * GetMenuItems returns active menu items from local SQLite.
 * If categoryID is non-empty, filters by category.
 */
export function GetMenuItems(categoryID: string): $CancellablePromise<model$0.MenuItemWithCategory[]> {
    return $Call.ByID(694497674, categoryID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PreCacheImages(imageURLs: string[]): $CancellablePromise<void> {
    return $Call.ByID(4022251980, imageURLs);
}

// Private type creation functions
const $$createType0 = model$0.Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.InventoryItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.MenuItemWithCategory.createFrom;
const $$createType5 = $Create.Array($$createType4);
