// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagementService is a Wails-bound service that proxies management
 * operations to the central API. After each write, it triggers a local
 * sync to refresh the SQLite cache.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdjustStock adjusts stock for a raw material via the API.
 */
export function AdjustStock(inventoryItemID: string, delta: number, reason: string): $CancellablePromise<void> {
    return $Call.ByID(1588050323, inventoryItemID, delta, reason);
}

/**
 * CreateCategory creates a new category via the API.
 */
export function CreateCategory(nameAr: string, sortOrder: number): $CancellablePromise<model$0.Category | null> {
    return $Call.ByID(1200835244, nameAr, sortOrder).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateInventoryItem creates a new raw material via the API.
 */
export function CreateInventoryItem(nameAr: string, baseUnitAr: string, stockQty: number, lowStockThreshold: number, unitCost: number): $CancellablePromise<model$0.InventoryItem | null> {
    return $Call.ByID(1771400047, nameAr, baseUnitAr, stockQty, lowStockThreshold, unitCost).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateMenuItem creates a new menu item via the API.
 */
export function CreateMenuItem(categoryID: string, nameAr: string, price: number, costCalcMethod: string, manualCostPrice: number): $CancellablePromise<model$0.MenuItemWithCategory | null> {
    return $Call.ByID(2560109324, categoryID, nameAr, price, costCalcMethod, manualCostPrice).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CreateTable creates a new restaurant table via the API.
 */
export function CreateTable($number: string): $CancellablePromise<model$0.Table | null> {
    return $Call.ByID(3214074472, $number).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeleteCategory deletes a category via the API.
 */
export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(1502861615, id);
}

/**
 * DeleteInventoryItem soft-deletes a raw material via the API.
 */
export function DeleteInventoryItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(2094520518, id);
}

/**
 * DeleteMenuItem soft-deletes a menu item via the API.
 */
export function DeleteMenuItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(3735835763, id);
}

/**
 * DeleteTable deletes a restaurant table via the API.
 */
export function DeleteTable(id: string): $CancellablePromise<void> {
    return $Call.ByID(2883097645, id);
}

/**
 * GetRecipe fetches the recipe for a menu item from the API.
 */
export function GetRecipe(menuItemID: string): $CancellablePromise<model$0.RecipeIngredientWithDetails[]> {
    return $Call.ByID(2791811370, menuItemID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListTables fetches all restaurant tables from the API.
 */
export function ListTables(): $CancellablePromise<model$0.Table[]> {
    return $Call.ByID(3633872989).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SetRecipe sets/updates the recipe for a menu item via the API.
 */
export function SetRecipe(menuItemID: string, ingredients: $models.RecipeIngredientInput[]): $CancellablePromise<void> {
    return $Call.ByID(4058401390, menuItemID, ingredients);
}

/**
 * TriggerSync manually triggers a full sync (pull + push).
 */
export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(3465993359);
}

/**
 * UpdateCategory updates a category via the API.
 */
export function UpdateCategory(id: string, nameAr: string, sortOrder: number): $CancellablePromise<model$0.Category | null> {
    return $Call.ByID(2724532653, id, nameAr, sortOrder).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateInventoryItem updates a raw material via the API.
 */
export function UpdateInventoryItem(id: string, nameAr: string, baseUnitAr: string, stockQty: number, lowStockThreshold: number, unitCost: number): $CancellablePromise<model$0.InventoryItem | null> {
    return $Call.ByID(3146448404, id, nameAr, baseUnitAr, stockQty, lowStockThreshold, unitCost).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateMenuItem updates a menu item via the API.
 */
export function UpdateMenuItem(id: string, categoryID: string, nameAr: string, price: number, costCalcMethod: string, manualCostPrice: number): $CancellablePromise<model$0.MenuItemWithCategory | null> {
    return $Call.ByID(3825037861, id, categoryID, nameAr, price, costCalcMethod, manualCostPrice).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.InventoryItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.MenuItemWithCategory.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.Table.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.RecipeIngredientWithDetails.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType6);
