// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagementService is a Wails-bound service for admin operations.
 * All writes go to local SQLite first, then get queued for async push to the API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdjustStock adjusts stock for a raw material locally and queues for API push.
 */
export function AdjustStock(inventoryItemID: string, delta: number, reason: string): $CancellablePromise<void> {
    return $Call.ByID(1588050323, inventoryItemID, delta, reason);
}

/**
 * CreateCategory creates a new category locally and queues for API push.
 */
export function CreateCategory(nameAr: string, sortOrder: number): $CancellablePromise<model$0.Category | null> {
    return $Call.ByID(1200835244, nameAr, sortOrder).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateInventoryItem creates a new raw material locally and queues for API push.
 */
export function CreateInventoryItem(nameAr: string, baseUnitAr: string, stockQty: number, lowStockThreshold: number, unitCost: number): $CancellablePromise<model$0.InventoryItem | null> {
    return $Call.ByID(1771400047, nameAr, baseUnitAr, stockQty, lowStockThreshold, unitCost).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateMenuItem creates a new menu item locally and queues for API push.
 */
export function CreateMenuItem(categoryID: string, nameAr: string, price: number, costCalcMethod: string, manualCostPrice: number, imagePath: string): $CancellablePromise<model$0.MenuItemWithCategory | null> {
    return $Call.ByID(2560109324, categoryID, nameAr, price, costCalcMethod, manualCostPrice, imagePath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CreateTable creates a new table locally with a temporary token and queues for API push.
 */
export function CreateTable($number: string): $CancellablePromise<model$0.Table | null> {
    return $Call.ByID(3214074472, $number).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeleteCategory deletes a category locally and queues for API push.
 */
export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(1502861615, id);
}

/**
 * DeleteInventoryItem soft-deletes a raw material locally and queues for API push.
 */
export function DeleteInventoryItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(2094520518, id);
}

/**
 * DeleteMenuItem soft-deletes a menu item locally and queues for API push.
 */
export function DeleteMenuItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(3735835763, id);
}

/**
 * DeleteTable soft-deletes a table locally and queues for API push.
 */
export function DeleteTable(id: string): $CancellablePromise<void> {
    return $Call.ByID(2883097645, id);
}

/**
 * GetRecipe fetches the recipe for a menu item from local SQLite.
 */
export function GetRecipe(menuItemID: string): $CancellablePromise<model$0.RecipeIngredientWithDetails[]> {
    return $Call.ByID(2791811370, menuItemID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetTableQRCode generates a QR code for a table's web menu link.
 * Returns an error message if the table hasn't been synced yet (no real token).
 */
export function GetTableQRCode(tableToken: string, menuBaseURL: string): $CancellablePromise<string> {
    return $Call.ByID(233827386, tableToken, menuBaseURL);
}

/**
 * ListTables fetches all tables from local SQLite.
 */
export function ListTables(): $CancellablePromise<model$0.Table[]> {
    return $Call.ByID(3633872989).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SetRecipe sets/updates the recipe for a menu item locally and queues for API push.
 */
export function SetRecipe(menuItemID: string, ingredients: $models.RecipeIngredientInput[]): $CancellablePromise<void> {
    return $Call.ByID(4058401390, menuItemID, ingredients);
}

/**
 * TriggerSync manually triggers a full sync (pull + push).
 */
export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(3465993359);
}

/**
 * UpdateCategory updates a category locally and queues for API push.
 */
export function UpdateCategory(id: string, nameAr: string, sortOrder: number): $CancellablePromise<model$0.Category | null> {
    return $Call.ByID(2724532653, id, nameAr, sortOrder).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateInventoryItem updates a raw material locally and queues for API push.
 */
export function UpdateInventoryItem(id: string, nameAr: string, baseUnitAr: string, stockQty: number, lowStockThreshold: number, unitCost: number): $CancellablePromise<model$0.InventoryItem | null> {
    return $Call.ByID(3146448404, id, nameAr, baseUnitAr, stockQty, lowStockThreshold, unitCost).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateMenuItem updates a menu item locally and queues for API push.
 */
export function UpdateMenuItem(id: string, categoryID: string, nameAr: string, price: number, costCalcMethod: string, manualCostPrice: number, imagePath: string): $CancellablePromise<model$0.MenuItemWithCategory | null> {
    return $Call.ByID(3825037861, id, categoryID, nameAr, price, costCalcMethod, manualCostPrice, imagePath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UploadMenuItemImage uploads an image file to the API (network required).
 */
export function UploadMenuItemImage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1127396906, filePath);
}

// Private type creation functions
const $$createType0 = model$0.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.InventoryItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.MenuItemWithCategory.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.Table.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.RecipeIngredientWithDetails.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType6);
