// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIConnection holds the stored API connection details.
 */
export class APIConnection {
    "api_url": string;

    /**
     * format: "user@tenant-slug"
     */
    "username": string;
    "password": string;

    /** Creates a new APIConnection instance. */
    constructor($$source: Partial<APIConnection> = {}) {
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): APIConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIConnection($$parsedSource as Partial<APIConnection>);
    }
}

/**
 * DailyReportEntry is a single-day aggregation within a range report.
 */
export class DailyReportEntry {
    "date": string;
    "order_count": number;
    "total_sales": number;

    /** Creates a new DailyReportEntry instance. */
    constructor($$source: Partial<DailyReportEntry> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("order_count" in $$source)) {
            this["order_count"] = 0;
        }
        if (!("total_sales" in $$source)) {
            this["total_sales"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReportEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyReportEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyReportEntry($$parsedSource as Partial<DailyReportEntry>);
    }
}

/**
 * LocalUser represents a user stored in local SQLite for PIN auth.
 */
export class LocalUser {
    "id": string;
    "name_ar": string;
    "role": string;

    /** Creates a new LocalUser instance. */
    constructor($$source: Partial<LocalUser> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalUser instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalUser {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalUser($$parsedSource as Partial<LocalUser>);
    }
}

/**
 * ProfitReport contains profit/loss data for a date range.
 */
export class ProfitReport {
    "total_sales": number;
    "total_recipe_cost": number;
    "gross_profit": number;
    "profit_margin": number;
    "order_count": number;
    "voided_count": number;
    "top_items": TopSellingItem[];
    "sales_by_source": { [_ in string]?: number };
    "daily_breakdown": DailyReportEntry[];

    /** Creates a new ProfitReport instance. */
    constructor($$source: Partial<ProfitReport> = {}) {
        if (!("total_sales" in $$source)) {
            this["total_sales"] = 0;
        }
        if (!("total_recipe_cost" in $$source)) {
            this["total_recipe_cost"] = 0;
        }
        if (!("gross_profit" in $$source)) {
            this["gross_profit"] = 0;
        }
        if (!("profit_margin" in $$source)) {
            this["profit_margin"] = 0;
        }
        if (!("order_count" in $$source)) {
            this["order_count"] = 0;
        }
        if (!("voided_count" in $$source)) {
            this["voided_count"] = 0;
        }
        if (!("top_items" in $$source)) {
            this["top_items"] = [];
        }
        if (!("sales_by_source" in $$source)) {
            this["sales_by_source"] = {};
        }
        if (!("daily_breakdown" in $$source)) {
            this["daily_breakdown"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfitReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfitReport {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_items" in $$parsedSource) {
            $$parsedSource["top_items"] = $$createField6_0($$parsedSource["top_items"]);
        }
        if ("sales_by_source" in $$parsedSource) {
            $$parsedSource["sales_by_source"] = $$createField7_0($$parsedSource["sales_by_source"]);
        }
        if ("daily_breakdown" in $$parsedSource) {
            $$parsedSource["daily_breakdown"] = $$createField8_0($$parsedSource["daily_breakdown"]);
        }
        return new ProfitReport($$parsedSource as Partial<ProfitReport>);
    }
}

/**
 * RecipeIngredientInput is the frontend input for a single recipe ingredient.
 */
export class RecipeIngredientInput {
    "inventory_item_id": string;
    "quantity": number;

    /** Creates a new RecipeIngredientInput instance. */
    constructor($$source: Partial<RecipeIngredientInput> = {}) {
        if (!("inventory_item_id" in $$source)) {
            this["inventory_item_id"] = "";
        }
        if (!("quantity" in $$source)) {
            this["quantity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecipeIngredientInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RecipeIngredientInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecipeIngredientInput($$parsedSource as Partial<RecipeIngredientInput>);
    }
}

/**
 * TopSellingItem represents a top-selling menu item.
 */
export class TopSellingItem {
    "name_ar": string;
    "total_qty": number;
    "total_revenue": number;

    /** Creates a new TopSellingItem instance. */
    constructor($$source: Partial<TopSellingItem> = {}) {
        if (!("name_ar" in $$source)) {
            this["name_ar"] = "";
        }
        if (!("total_qty" in $$source)) {
            this["total_qty"] = 0;
        }
        if (!("total_revenue" in $$source)) {
            this["total_revenue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopSellingItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopSellingItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopSellingItem($$parsedSource as Partial<TopSellingItem>);
    }
}

// Private type creation functions
const $$createType0 = TopSellingItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = DailyReportEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
