// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OrderService is a Wails-bound service for creating and managing orders.
 * All exported methods are callable from the Vue frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateOrder is called from the frontend when the cashier confirms checkout.
 * 1. Generates UUID + local daily order number
 * 2. Inserts order + order_items into SQLite
 * 3. Runs the recipe engine to deduct local inventory
 * 4. Returns the created order
 */
export function CreateOrder(items: model$0.CartItem[], paymentMethod: string): $CancellablePromise<model$0.OrderWithItems | null> {
    return $Call.ByID(2109256473, items, paymentMethod).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetOrdersByDateRange returns orders between from and to dates (inclusive).
 * Dates should be in "YYYY-MM-DD" format.
 */
export function GetOrdersByDateRange($from: string, to: string): $CancellablePromise<model$0.OrderWithItems[]> {
    return $Call.ByID(3548838598, $from, to).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTodayOrderCount returns the count of today's orders (for display in header).
 */
export function GetTodayOrderCount(): $CancellablePromise<number> {
    return $Call.ByID(3721626433);
}

/**
 * GetTodayOrders returns all orders created today.
 */
export function GetTodayOrders(): $CancellablePromise<model$0.OrderWithItems[]> {
    return $Call.ByID(2673709467).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * VoidOrder marks a completed order as voided. No stock reversal.
 */
export function VoidOrder(orderID: string): $CancellablePromise<model$0.Order | null> {
    return $Call.ByID(2378986995, orderID).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.OrderWithItems.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = model$0.Order.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
