// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReceiptService is a Wails-bound service for receipt printing.
 * It generates ESC/POS formatted receipts for thermal printers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetReceiptText returns the formatted receipt text for display/preview.
 * Callable from the frontend for a print preview.
 */
export function GetReceiptText(order: model$0.OrderWithItems): $CancellablePromise<string> {
    return $Call.ByID(2968782964, order);
}

/**
 * PrintReceipt generates and sends a receipt to the connected thermal printer.
 * Best-effort: logs errors but returns them so the frontend can show a warning.
 */
export function PrintReceipt(order: model$0.OrderWithItems): $CancellablePromise<void> {
    return $Call.ByID(6227570, order);
}
