// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReportService is a Wails-bound service for profit reports.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetProfitReport generates a profit report for a date range.
 * from and to should be in "YYYY-MM-DD" format.
 */
export function GetProfitReport($from: string, to: string): $CancellablePromise<$models.ProfitReport | null> {
    return $Call.ByID(2897962931, $from, to).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfitReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
