// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService is a Wails-bound service that exposes sync engine health
 * and controls to the frontend dashboard.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../sync/models.js";

/**
 * GetAuditConflicts returns only conflict entries from the audit log.
 */
export function GetAuditConflicts(limit: number): $CancellablePromise<sync$0.AuditLogEntry[]> {
    return $Call.ByID(2081302886, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAuditLog returns the most recent N sync audit log entries from persistent storage.
 * This is useful for debugging sync issues — entries survive app restarts.
 */
export function GetAuditLog(limit: number): $CancellablePromise<sync$0.AuditLogEntry[]> {
    return $Call.ByID(1151528475, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFailedOrderCount returns count of dead-lettered orders (synced=2).
 */
export function GetFailedOrderCount(): $CancellablePromise<number> {
    return $Call.ByID(2025143666);
}

/**
 * GetFailedOrders returns the list of dead-lettered orders with error details.
 */
export function GetFailedOrders(): $CancellablePromise<sync$0.FailedOrderInfo[]> {
    return $Call.ByID(1734460768).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetPendingOrderCount returns count of unsynced orders (synced=0).
 */
export function GetPendingOrderCount(): $CancellablePromise<number> {
    return $Call.ByID(1261131568);
}

/**
 * GetSyncLogs returns recent sync log entries.
 */
export function GetSyncLogs(): $CancellablePromise<sync$0.SyncLogEntry[]> {
    return $Call.ByID(1603810340).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSyncStatus returns the full sync health snapshot for the dashboard.
 */
export function GetSyncStatus(): $CancellablePromise<sync$0.SyncStatusSnapshot | null> {
    return $Call.ByID(3611596121).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ResetSyncState clears all sync_meta timestamps. The next sync cycle will be a full sync.
 */
export function ResetSyncState(): $CancellablePromise<void> {
    return $Call.ByID(14582765);
}

/**
 * RetryFailedOrders resets dead-lettered orders (synced=2) back to pending (synced=0).
 */
export function RetryFailedOrders(): $CancellablePromise<number> {
    return $Call.ByID(2028951426);
}

/**
 * TriggerFullSync clears all sync timestamps and triggers a full re-sync.
 */
export function TriggerFullSync(): $CancellablePromise<void> {
    return $Call.ByID(2095141870);
}

/**
 * TriggerSync manually triggers a pull + push cycle.
 */
export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(194308559);
}

// Private type creation functions
const $$createType0 = sync$0.AuditLogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = sync$0.FailedOrderInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = sync$0.SyncLogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = sync$0.SyncStatusSnapshot.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
