// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyUpdate(installerPath: string): $CancellablePromise<void> {
    return $Call.ByID(1431080139, installerPath);
}

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1299878840).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DownloadUpdate(downloadURL: string): $CancellablePromise<string> {
    return $Call.ByID(1569906819, downloadURL);
}

export function GetDownloadProgress(): $CancellablePromise<number> {
    return $Call.ByID(2368392241);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
