// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebOrderService manages incoming web menu orders on the POS side.
 * It is Wails-bound so the Vue frontend can call its methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../sync/models.js";

/**
 * AcceptOrder accepts a pending order, triggers stock deduction, and updates the API.
 */
export function AcceptOrder(orderID: string): $CancellablePromise<void> {
    return $Call.ByID(2693326279, orderID);
}

/**
 * CompleteOrder marks an accepted order as completed and updates the API.
 */
export function CompleteOrder(orderID: string): $CancellablePromise<void> {
    return $Call.ByID(1151111078, orderID);
}

/**
 * GetAcceptedOrders returns accepted (in-progress) web orders.
 */
export function GetAcceptedOrders(): $CancellablePromise<model$0.OrderWithItems[]> {
    return $Call.ByID(2556388279).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCompletedOrders returns completed web orders.
 */
export function GetCompletedOrders(): $CancellablePromise<model$0.OrderWithItems[]> {
    return $Call.ByID(2016954133).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPendingOrders returns current pending web orders.
 */
export function GetPendingOrders(): $CancellablePromise<model$0.OrderWithItems[]> {
    return $Call.ByID(2969541899).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HandleSSEEvent processes an SSE event from the API.
 * Called by the SSE client callback — not exposed to frontend.
 */
export function HandleSSEEvent(event: sync$0.SSEEvent): $CancellablePromise<void> {
    return $Call.ByID(3881286328, event);
}

/**
 * RejectOrder rejects a pending order and updates the API.
 */
export function RejectOrder(orderID: string): $CancellablePromise<void> {
    return $Call.ByID(2960003250, orderID);
}

// Private type creation functions
const $$createType0 = model$0.OrderWithItems.createFrom;
const $$createType1 = $Create.Array($$createType0);
